spring.application.name=demo-springboot

# este arquivo application.properties é o arquivo de configuração do Spring Boot. Ele é usado para configurar as propriedades do aplicativo, como a porta do servidor, o nome do aplicativo, etc. O Spring Boot tem uma série de propriedades pré-definidas que podem ser configuradas nesse arquivo, e também permite criar propriedades personalizadas para serem usadas no aplicativo.
#  é onde informamos as propriedades do aplicativo, como a porta do servidor, o nome do aplicativo, etc. O Spring Boot tem uma série de propriedades pré-definidas que podem ser configuradas nesse arquivo, e também permite criar propriedades personalizadas para serem usadas no aplicativo.

#  dados de conexao com o banco de dados

#  o arquivo será salvo no diretorio ./data do proprio projeto, pois o ponto . referencia o projeto.


spring.datasource.url=jdbc:h2:file:./data/demo-springboot
spring.datasource.username=sa
spring.datasource.password=
spring.datasource.driver-class-name=org.h2.Driver
spring.h2.console.enabled=true
#  habilitamos um console pra se comunicar ocm o banco h2 e ver o que tem la dentro
#  nao precisará informar senha, por isso esta vazia

#  queremos que as tabelas, que representam as entidades do nosso projeto, sejam automaticamente ciradas no banco.
#  (pois a demo precisa ser criada automaticamente no banco)
#  por isso, habilitamos essas 2 opcoes, ref. ao jpa
spring.jpa.generate-ddl=true
spring.jpa.hibernate.ddl-auto=update




# o banco h2 é o driver
#  h2 é um banco de dados em memória, que é usado para desenvolvimento e testes. Ele é leve e fácil de usar, e não requer configuração adicional. 
# O h2 é uma boa opção para desenvolvimento e testes, mas não é recomendado para produção, pois ele não é tão robusto quanto outros bancos de dados, como o MySQL ou o PostgreSQL.


#  Inserimos, atraves do localhost:8080/h2-console, dados
#  INSERT INTO DEMO VALUES ('1', 'MINHA DEMO SOBRE SPRING BOOT');
# acessamos http://localhost:8080/demo/1 e isso mostrou http://localhost:8080/demo/1 (aba JSON)
#  foi e fato feito o insert, a demo é retornada pelo endpoint, e a demo foi salva no banco de dados h2, pois o endpoint chama o serviço, e o serviço chama o repositório, que salva a demo no banco de dados. 
# O endpoint é responsável por receber as requisições, o serviço é responsável por realizar as operações de negócio, e o repositório é responsável por acessar o banco de dados.